### ISSUE TITLE
[CFFDRS R Bug]: https://r-forge.r-project.org/tracker/?func=detail&atid=5372&aid=6804&group_id=1970

### ISSUE THREAD

**Issue by rsbivand** [cffdrs/cffdrs_r#36]
### What happened?

If you avoid all things posit, and use minimally tools provided with R, you avoid lots of headaches. I note that cffdrs had no reverse dependencies of any kind (strong or weak) on October 13, 2023, the last check I made before rgdal was archived. So perhaps simply ignore posit noise?

Running `R CMD check --as-cran cffdrs_1.10.0.tar.gz` after `R CMD build cffdrs_r-dev` from a zip download of the github repo gives the following failing log: 
[00check.log](https://github.com/cffdrs/cffdrs_r/files/13998044/00check.log)

### Approvals Process

- [ ] Testing For Issue
- [ ] Merge

**Comment by BadgerOnABike** [comment]
Thank you so much! Submitted and awaiting patiently :)
