### ISSUE TITLE
[CFFDRS R Bug]: Handle not having FUELTYPE defined properly in `fbp()`

### ISSUE THREAD

**Issue by jordan-evens** [cffdrs/cffdrs_r#40]
### What happened?

`df_fbp <- fbp(df_wx_out, output = "ALL")`

gives:
`Error in slope_values[["WSV"]] : subscript out of bounds`
when no FUELTYPE defined

### Approvals Process

- [ ] Testing For Issue
- [ ] Merge

**Comment by BadgerOnABike** [comment]
Ah yea, we check if input exists, but not if the stuff in input exists!
