### ISSUE TITLE
[CFFDRS R Bug]: Slopecalc.r - WSV/RAZ calculations only provided for "NF" and "WA" fuel types

### ISSUE THREAD

**Issue by gagreene** [cffdrs/cffdrs_r#45]
### Contact Details

map.n.trowel@gmail.com

### Issue
- The WSV and RAZ calculations on lines 288 to 327 of Slopecalc.r are only generated for the "NF" and "WA" fuel types when they are present in tabularized data. If absent, the function works as intended.

### Cause
- The causes are two-fold:
    - (1) For tabularized data (e.g., rasters), the return function causes the code to exit Slopecalc.r if any "NF" or "WA" fuel types are encountered, thereby skipping the calculations for all other fuel types. 
    - (2) The return function doesn't vectorize the NA values as intended. This results in a list of NA values as output.

### Solution
- A proposed solution is as follows:
    - (1) Calculate WSV and RAZ for everything first
    - (2) Set WSV and RAZ as NA for "NF" and "WA" fuel types (if this is the desired result)
    - (3) Return the final WSV and RAZ calculations

### Approvals Process

- [ ] Testing For Issue
- [ ] Merge

**Comment by BadgerOnABike** [comment]
Thank you for the solution, merged. Apologies on the delays.

**Comment by gagreene** [comment]
Any time! Happy to help
